diamond:
  - DIAMOND_BOOTS
  - DIAMOND_LEGGINGS
  - DIAMOND_CHESTPLATE
  - DIAMOND_HELMET
  - DIAMOND_SWORD
iron:
  - IRON_BOOTS
  - IRON_LEGGINGS
  - IRON_CHESTPLATE
  - IRON_HELMET
  - IRON_SWORD
leather:
  - LEATHER_BOOTS
  - LEATHER_LEGGINGS
  - LEATHER_CHESTPLATE
  - LEATHER_HELMET
  - STONE_SWORD